# fly.preview.toml
app = "spazio-solazzo"
primary_region = "ams"
kill_signal = "SIGTERM"

[build]
dockerfile = "Dockerfile"

[env]
PHX_SERVER = "true"
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
type = "connections"
soft_limit = 500
hard_limit = 500

[[vm]]
cpu_kind = "shared"
memory = '512mb'
cpus = 1
memory_mb = 512
